### ISSUE TITLE
Nested Nodes ordering instable

### ISSUE THREAD

**Issue by florian42** [reaviz/reaflow#92] opened 2021-07-21 09:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When working with expanding and collapsing nested nodes, reaflow seems to change the ordering of the nodes (even though the sequence of the input arrays stays similar).

## Expected behavior

I would expect reaflow not to change the ordering of the nodes on the canvas depending on if it needs to draw edges to children or not.

## Minimal reproduction of the problem with instructions

To reproduce the problem, note in which sequence the nodes are laid out on the canvas. Then click on nodes 2 and 3 to expand or collapse them, which will display the children of nodes 2 and 3.

I recorded a gif that demonstrates the problematic behaviour:

![CleanShot 2021-07-21 at 11 10 02](https://user-images.githubusercontent.com/9154541/126463529-cd0503e1-e1c5-49b4-a221-caa81f5ee0d8.gif)

You can play around with that example here: https://codesandbox.io/s/vigorous-agnesi-nzl6f

## What is the motivation / use case for changing the behavior?

From a user's perspective,  nodes changing where they are displayed can confuse and make it difficult to understand complex graphs.

## Environment

<pre><code>
Libs:
- react version: 17.0.2
- reaflow: 3.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
The code sandbox example is a bit hacky. I hope that doesn't distract from the actual issue.

@amcdnl I'm happy to contribute, but I need guidance/pointers on where to start investigating?

**Comment by amcdnl** [comment] 2021-07-21 12:19
Thanks for all the info, however, I'm still not sure I follow what the problem is. Can you provide a diagram of how it works today and what you would expect?

I'm going to bet this is ELKJS rather than reaflow directly ...

**Comment by florian42** [comment] 2021-07-21 14:37
**Problem**: The problem is that the nodes switch positions on the canvas when collapsing or expanding a node with children. When looking at the gif I uploaded above, focus on the nodes that are far on the left. Node 1 will suddenly switch position with Node 4.

**Expectation**: I think the nodes should never switch positions.

What kind of Diagram would help? Should I give the nodes in the example I posted above a unique colour?

**Comment by amcdnl** [comment] 2021-07-21 14:49
Oh I see - I missed that. I'm working on an enhancement today and I'll check it out while im working on it.

**Comment by amcdnl** [comment] 2021-08-30 11:41
Collapse and expand isn't built in out of the box but essentially all you need to do is manipulate your graph. I will try to put together a demo on this!

**Comment by jamesgade** [comment] 2022-08-17 06:27
getting includes type error after reaflow 4.0.0 later versions,how to resolve includes type error.
<img width="1920" alt="Screenshot 2022-08-17 at 11 55 08 AM" src="https://user-images.githubusercontent.com/92790321/185049608-a7a08d0e-07b9-4fea-b000-858547e8b050.png">

**Comment by Vishal-Isharani** [comment] 2022-11-05 06:18
The same is happening with a simple list of nodes, Check out this https://react-3qjytm.stackblitz.io

**Comment by AykutSarac** [comment] 2023-08-04 10:16
This seem to be solved now.

**Comment by amcdnl** [comment] 2023-08-04 11:13
YES! Sorry forgot to close it!

**Closed by amcdnl** 2023-08-04 11:13 UTC
Labels: bug
